trigger:
  - main

pool:
  vmImage: 'macOS-latest'

steps:
# Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

# Install Appium
- script: |
    echo "Installing Appium..."
    npm install -g appium
  displayName: 'Install Appium'

# Install Java 8 and start emulator with boot check
- script: |
    echo "Installing JDK 8 for Android SDK tools..."
    brew tap homebrew/cask-versions
    brew install --cask temurin8

    export JAVA_HOME=$(/usr/libexec/java_home -v1.8)
    echo "Using Java at $JAVA_HOME"

    echo "Installing Android system image..."
    echo "y" | $ANDROID_HOME/tools/bin/sdkmanager "system-images;android-30;google_apis;x86"

    echo "Creating AVD..."
    echo "no" | $ANDROID_HOME/tools/bin/avdmanager create avd -n Pixel_API_30 -k "system-images;android-30;google_apis;x86" --force

    echo "Starting Android Emulator..."
    $ANDROID_HOME/emulator/emulator -avd Pixel_API_30 -no-window -no-audio -no-boot-anim &

    echo "Waiting for emulator to boot..."
    $ANDROID_HOME/platform-tools/adb wait-for-device

    bootanim=""
    until [[ "$bootanim" == *"stopped"* ]]; do
      sleep 5
      bootanim=$($ANDROID_HOME/platform-tools/adb shell getprop init.svc.bootanim 2>/dev/null)
      echo "Waiting for boot animation to stop... ($bootanim)"
    done

    echo "Emulator is ready."
    $ANDROID_HOME/platform-tools/adb devices
  displayName: 'Start Android Emulator on macOS'

# Run Katalon with emulator
- task: katalonTask@1
  inputs:
    version: '10.1.1'
    executeArgs: >
      -retry=0
      -testSuitePath="Test Suites/WRMA Android Regression-GuestMode"
      -browserType="Android"
      -deviceId="emulator-5554"
      -executionProfile="WRMA-Android"
      -apiKey="61282ee6-82bb-48f4-bb3f-fb469f4b2123"
      -orgID=1958469
      --config
      -proxy.auth.option=NO_PROXY
      -proxy.system.option=NO_PROXY
      -proxy.system.applyToDesiredCapabilities=true
      -webui.autoUpdateDrivers=true
      -appiumDirectory="/usr/local/lib/node_modules/appium"
  displayName: 'Run Katalon Test Suite'