trigger:
- main
 
pool:
  vmImage: 'windows-latest'
 
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'
 
- script: |
    echo Starting Android Emulator...
    cd "%ANDROID_HOME%\emulator"
    emulator -avd Pixel_API_30 -no-window -no-audio -no-boot-anim &
  displayName: 'Start Android Emulator'
 
- task: katalonTask@1
  inputs:
    version: '10.1.1'
    executeArgs: >
      -retry=0
      -testSuitePath="Test Suites/demo"
      -browserType="Android"
      -deviceId="emulator-5554"
      -executionProfile="WRMA-Android"
      -apiKey="61282ee6-82bb-48f4-bb3f-fb469f4b2123"
      -orgID=your-org-id
      --config
      -proxy.auth.option=NO_PROXY
      -proxy.system.option=NO_PROXY
      -proxy.system.applyToDesiredCapabilities=true
      -webui.autoUpdateDrivers=true
      -appiumDirectory="C:\\Users\\VssAdministrator\\AppData\\Roaming\\npm\\node_modules\\appium"